<?php //generated by esnc.net setup wizard
/**** MULTI WEBSITE SUPPORT. DISCOVER CONFIG ON DOMAIN NAME. MUST REMOVED ON DEPLOYMENT ****/
return include '/hsphere/local/home/aaalqze/vietnam-cambodia-tours.com/config.php';
?>