<?php //generated by linkbuilding.esnc.net setup wizard
define('DOMAIN_ID',60);
define('USER_EMAIL','guest@esnadvanced.com');
define('USER_PASS','WjNWbGMzUT0=');
define('URL_LINKEXCHANGE_SERVICES','http://links.esnc.net/services.php');

define('SATELLITE_SETUP',							0);
define('SATELLITE_CAT_ITEMS_UPDATE',				1);
define('SATELLITE_CATS_UPDATE',						2);
define('SATELLITE_ITEMS_UPDATE',					3);
define('SATELLITE_CATS_DELETE',						4);
define('SATELLITE_ITEMS_DELETE',					5);
define('SATELLITE_ACT_GET_ALL_CATLINKEXCHANGE',	6);
define('SATELLITE_ACT_GET_LINKEXCHANGE',			7);
define('SATELLITE_ACT_SETUP_LINKEXCHANGE_PAGE',			8);

define('ACT_GET_ALL_CATLINKEXCHANGE',				0);
define('ACT_GET_ALL_LINKEXCHANGE',					1);
define('ACT_GET_ALL_CATLINKEXCHANGELINKEXCHANGE',	2);
define('ACT_GET_CATLINKEXCHANGE',					3);
define('ACT_GET_LINKEXCHANGE',						4);
define('ACT_GET_CATLINKEXCHANGELINKEXCHANGE',		5);
define('ACT_OPEN_CATLINKEXCHANGE',					6);
define('ACT_OPEN_LINKEXCHANGE',						7);
define('ACT_SETUP_LINKEXCHANGE_PAGE',				9);

define('LINKEX_PAGESIZE',40);

define('CATLINKEXCHANGE_CTRL_SHOW',		1);
define('LINKEXCHANGE_CTRL_WAIT1',		1);
define('LINKEXCHANGE_CTRL_WAIT2',		2);
define('LINKEXCHANGE_CTRL_WAIT3',		4);
define('LINKEXCHANGE_CTRL_SHOW',		8);
define('LINKEXCHANGE_CTRL_OVERWRITE',	16);
define('LINKEX_SORTBY_VIEW_DESC',				1);
define('LINKEX_SORTBY_VIEW_ASC',				0);
define('LINKEX_SORTBY_NAME_DESC',				2);
define('LINKEX_SORTBY_NAME_ASC',				3);
define('LINKEX_SORTBY_CREATED_DESC',			5);
define('LINKEX_SORTBY_CREATED_ASC',				4);
define('LINKEX_SORTBY_ID_DESC',					7);
define('LINKEX_SORTBY_ID_ASC',					6);
$SORTBY = array(
		LINKEX_SORTBY_VIEW_DESC=>'`view` desc',
		LINKEX_SORTBY_VIEW_ASC=>'`view` asc',
		LINKEX_SORTBY_NAME_DESC=>'`name` desc',
		LINKEX_SORTBY_NAME_ASC=>'`name` asc',
		LINKEX_SORTBY_CREATED_DESC=>'`created` desc',
		LINKEX_SORTBY_CREATED_ASC=>'`created` asc',
		LINKEX_SORTBY_ID_DESC=>'`id` desc',
		LINKEX_SORTBY_ID_ASC=>'`id` asc',
		);
define('DATETIME_FORMAT_DB','%Y-%m-%d %H:%M:%S');
define('DATE_FORMAT_DB','%Y-%m-%d');
define('TIME_FORMAT_DB','%H:%M:%S');

function esnc_encode($s){ return base64_encode($s);}
function esnc_decode($s){ return base64_decode($s);}
function get_objects($url,$tagName,&$arr_item,$decode=null){
	$xml_parser = xml_parser_create();
	if($decode==true)$data = htmlspecialchars_decode(file_get_contents($url));else $data = file_get_contents($url);
	xml_parse_into_struct($xml_parser, $data, $doc, $index);
	xml_parser_free($xml_parser);
	$arr_item=array();$i=0;
	foreach ($doc as $elem) {
		if((($elem['type']=='open')||($elem['type']=='complete'))&&($elem['tag']==$tagName)){
			$arr_item[$i]=$elem['attributes'];
			$i++;
		}
	}
}
function linkexchangesetup(){
	$sql="DROP TABLE IF EXISTS `".DB_TABLE_PREFIX."catlinkexchange`";
	if(!mysql_query($sql))echo $sql."<br/>";
	$sql="CREATE TABLE `".DB_TABLE_PREFIX."catlinkexchange`(
			`id` bigint unsigned NOT null,`name` varchar(255) null default '',`desc` varchar(255) default null,`img1` varchar(255) default null,
			`alt1` varchar(255) default null,`view` bigint unsigned default null,`ctrl` bigint unsigned default null,`extra` varchar(255) default null,
			`parentid` bigint unsigned default null)";
	if(!mysql_query($sql))echo $sql."<br/>";
	$url=URL_LINKEXCHANGE_SERVICES.'?usermail='.USER_EMAIL.'&userpass='.esnc_decode(USER_PASS).'&act='.ACT_GET_ALL_CATLINKEXCHANGE.'&DMid='.DOMAIN_ID;	
	get_objects($url,'CATEGORY',$arr_item);
	if(count($arr_item)>0){
		$sql="INSERT INTO `".DB_TABLE_PREFIX."catlinkexchange`(`id`,`name`,`desc`,`img1`,`alt1`,`view`,`ctrl`,`parentid`) VALUES ";
		for($i=0;$i<count($arr_item)-1;$i++){
			$sql.="(".$arr_item[$i]['ID'].",'".mysql_real_escape_string(utf8_decode($arr_item[$i]['NAME']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['DESC']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['IMG1']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['ALT1']))."',".((($arr_item[$i]['VIEW']!=null)&&($arr_item[$i]['VIEW']!=''))?$arr_item[$i]['VIEW']:"null").",".((($arr_item[$i]['CTRL']!=null)&&($arr_item[$i]['CTRL']!=''))?$arr_item[$i]['CTRL']:"null").",".((($arr_item[$i]['PARENTID']!=null)&&($arr_item[$i]['PARENTID']!=''))?$arr_item[$i]['PARENTID']:"null")."),";
		}
		$sql.="(".$arr_item[$i]['ID'].",'".mysql_real_escape_string(utf8_decode($arr_item[$i]['NAME']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['DESC']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['IMG1']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['ALT1']))."',".((($arr_item[$i]['VIEW']!=null)&&($arr_item[$i]['VIEW']!=''))?$arr_item[$i]['VIEW']:"null").",".((($arr_item[$i]['CTRL']!=null)&&($arr_item[$i]['CTRL']!=''))?$arr_item[$i]['CTRL']:"null").",".((($arr_item[$i]['PARENTID']!=null)&&($arr_item[$i]['PARENTID']!=''))?$arr_item[$i]['PARENTID']:"null").")";		
		if(!mysql_query($sql))echo $sql."<br/>";
	}
	$sql="DROP TABLE IF EXISTS `".DB_TABLE_PREFIX."linkexchange`";
	if(!mysql_query($sql))echo $sql."<br/>";
	$sql="CREATE TABLE  `".DB_TABLE_PREFIX."linkexchange` (
			`id` bigint unsigned NOT null,`name` varchar(255) default '',`title` varchar(255) default '',`url` varchar(255) default '',
			`src` varchar(255) default null,`desc` text,`created` datetime NOT null default '0000-00-00 00:00:00',`lastupdate` datetime NOT null default '0000-00-00 00:00:00',
			`view` int unsigned default '0',`type` bigint unsigned not null default '0',`status` bigint unsigned not null default '0',`email` varchar(255) default null,
			`phone` varchar(255) default null,`address` varchar(255) default null,`extra` text,`ctrl` bigint unsigned not null default '0')";
	if(!mysql_query($sql))echo $sql."<br/>";
	$url=URL_LINKEXCHANGE_SERVICES.'?usermail='.USER_EMAIL.'&userpass='.esnc_decode(USER_PASS).'&act='.ACT_GET_ALL_LINKEXCHANGE.'&DMid='.DOMAIN_ID;	
	get_objects($url,'ITEM',$arr_item);
	if(count($arr_item)>0){
		$sql="INSERT INTO `".DB_TABLE_PREFIX."linkexchange`(`id`,`name`,`title`,`url`,`src`,`desc`,`created`,`lastupdate`,`view`,`type`,`status`,`email`,`phone`,`address`,`extra`,`ctrl`) VALUES ";
		for($i=0;$i<count($arr_item)-1;$i++){
			$sql.="(".$arr_item[$i]['ID'].",'".mysql_real_escape_string(utf8_decode($arr_item[$i]['NAME']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['TITLE']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['URL']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['SRC']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['DESC']))."','".mysql_real_escape_string($arr_item[$i]['CREATED'])."','".mysql_real_escape_string($arr_item[$i]['LASTUPDATE'])."',".((($arr_item[$i]['VIEW']!=null)&&($arr_item[$i]['VIEW']!=''))?$arr_item[$i]['VIEW']:"null").",".((($arr_item[$i]['TYPE']!=null)&&($arr_item[$i]['TYPE']!=''))?$arr_item[$i]['TYPE']:"null").",".((($arr_item[$i]['STATUS']!=null)&&($arr_item[$i]['STATUS']!=''))?$arr_item[$i]['STATUS']:"null").",'".mysql_real_escape_string(utf8_decode($arr_item[$i]['EMAIL']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['PHONE']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['ADDRESS']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['EXTRA']))."',".((($arr_item[$i]['CTRL']!=null)&&($arr_item[$i]['CTRL']!=''))?$arr_item[$i]['CTRL']:"null")."),";
		}
		$sql.="(".$arr_item[$i]['ID'].",'".mysql_real_escape_string(utf8_decode($arr_item[$i]['NAME']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['TITLE']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['URL']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['SRC']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['DESC']))."','".mysql_real_escape_string($arr_item[$i]['CREATED'])."','".mysql_real_escape_string($arr_item[$i]['LASTUPDATE'])."',".((($arr_item[$i]['VIEW']!=null)&&($arr_item[$i]['VIEW']!=''))?$arr_item[$i]['VIEW']:"null").",".((($arr_item[$i]['TYPE']!=null)&&($arr_item[$i]['TYPE']!=''))?$arr_item[$i]['TYPE']:"null").",".((($arr_item[$i]['STATUS']!=null)&&($arr_item[$i]['STATUS']!=''))?$arr_item[$i]['STATUS']:"null").",'".mysql_real_escape_string(utf8_decode($arr_item[$i]['EMAIL']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['PHONE']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['ADDRESS']))."','".mysql_real_escape_string(utf8_decode($arr_item[$i]['EXTRA']))."',".((($arr_item[$i]['CTRL']!=null)&&($arr_item[$i]['CTRL']!=''))?$arr_item[$i]['CTRL']:"null").")";
		if(!mysql_query($sql))echo 'linkexchange'."<br/>";
	}
	$sql="DROP TABLE IF EXISTS `".DB_TABLE_PREFIX."catlinkexchangelinkexchange`";
	if(!mysql_query($sql))echo $sql."<br/>";
	$sql="CREATE TABLE  `".DB_TABLE_PREFIX."catlinkexchangelinkexchange` (
			`catlinkexchangeid` bigint unsigned NOT null,
			`linkexchangeid` bigint unsigned NOT null,
			`view` bigint unsigned default null)";
	if(!mysql_query($sql))echo 'catlinkexchangelinkexchange'."<br/>";
	$url=URL_LINKEXCHANGE_SERVICES.'?usermail='.USER_EMAIL.'&userpass='.esnc_decode(USER_PASS).'&act='.ACT_GET_ALL_CATLINKEXCHANGELINKEXCHANGE.'&DMid='.DOMAIN_ID;	
	get_objects($url,'RELATION',$arr_item);
	if(count($arr_item)>0){
		$sql="INSERT INTO `".DB_TABLE_PREFIX."catlinkexchangelinkexchange`(`catlinkexchangeid`,`linkexchangeid`,`view`) VALUES ";
		for($i=0;$i<count($arr_item)-1;$i++){
			$sql.="(".$arr_item[$i]['CATLINKEXCHANGEID'].",".$arr_item[$i]['LINKEXCHANGEID'].",".((($arr_item[$i]['VIEW']!=null)&&($arr_item[$i]['VIEW']!=''))?$arr_item[$i]['VIEW']:"null")."),";
		}
		$sql.="(".$arr_item[$i]['CATLINKEXCHANGEID'].",".$arr_item[$i]['LINKEXCHANGEID'].",".((($arr_item[$i]['VIEW']!=null)&&($arr_item[$i]['VIEW']!=''))?$arr_item[$i]['VIEW']:"null").")";
		if(!mysql_query($sql))echo $sql."<br/>";
	}
}
function catlinkexchangelist($parentid=null,$ctrl=null,$top=null){
	global $sql;
	$sql="SHOW TABLES LIKE '".DB_TABLE_PREFIX."catlinkexchange'";
	$row=mysql_fetch_array(mysql_query($sql));if(($row[0]==null)||($row[0]==""))linkexchangesetup();
	if(($ctrl==null)||(!is_int($ctrl))||($ctrl<=0))$ctrl=CATLINKEXCHANGE_CTRL_SHOW;
	if($top==null)$top=100000;
	$sql="SELECT `a`.`id`,`a`.`name`,`a`.`ctrl`,`a`.`img1`,`a`.`alt1`,`a`.`desc`,`a`.`view`,`a`.`parentid` FROM `".DB_TABLE_PREFIX."catlinkexchange` as `a` ";
	$sql.=" WHERE `a`.`ctrl`&".$ctrl."=".$ctrl;
	$sql.=(($parentid!=null)&&(is_int($parentid))&&($parentid>0))?" AND `a`.`parentid`=".$parentid:"";
	$sql.=" ORDER BY `a`.`view`,`a`.`id` LIMIT ".$top;
	return mysql_query($sql);	
}
function catlinkexchangeopen($id){
	global $sql;
	$sql="SHOW TABLES LIKE '".DB_TABLE_PREFIX."catlinkexchange'";
	$row=mysql_fetch_array(mysql_query($sql));if(($row[0]==null)||($row[0]==""))linkexchangesetup();
	settype($id,'int');
	$o=null;
	if(is_int($id)){
		$sql = "SELECT DISTINCT `a`.`id`,`a`.`name`,`a`.`ctrl`,`a`.`img1`,`a`.`alt1`,`a`.`desc`,`a`.`view`,`a`.`parentid` FROM `".DB_TABLE_PREFIX."catlinkexchange` as `a` WHERE `id`=".(int)$id;
		$o = mysql_fetch_object($rs = mysql_query($sql));
		mysql_free_result($rs);
	}
	return $o;
}
function linkexchangelist($catid=null,$ctrl=null,$qsearch=null,$sort=null,$top=null){
	global $sql,$SORTBY;
	$sql="SHOW TABLES LIKE '".DB_TABLE_PREFIX."catlinkexchange'";
	$row=mysql_fetch_array(mysql_query($sql));if(($row[0]==null)||($row[0]==""))linkexchangesetup();
	if($top==null)$top=100000;
	if($sort==null)$sort = LINKEX_SORTBY_VIEW_ASC;
	$wh = '';$tbcat='';$sort = $SORTBY[$sort];
	if(is_int($catid)) $tbcat = " INNER JOIN `".DB_TABLE_PREFIX."catlinkexchangelinkexchange` as `b` ON `id` = `b`.`linkexchangeid` AND `b`.`catlinkexchangeid` = ".$catid;
	else $tbcat = " INNER JOIN `".DB_TABLE_PREFIX."catlinkexchangelinkexchange` as `b` ON `id` = `b`.`linkexchangeid` ";
	if(($ctrl!=null)&&(is_int($ctrl))&&($ctrl>0))
		if(!is_array($ctrl))$wh = ' AND `a`.`ctrl`='.(int)$ctrl;
		else{
			$tmp='';
			foreach($ctrl as $i)$tmp .= ' OR `a`.`ctrl`='.(int)$i;
			$wh .= " AND(".substr($tmp,3).")";
		}
	if($qsearch)$wh .= ' AND (`a`.`title` like \'%'.mysql_real_escape_string($qsearch).'%\' OR `a`.`url` like \'%'.mysql_real_escape_string($qsearch).'%\' OR `a`.`src` like \'%'.mysql_real_escape_string($qsearch).'%\' OR `a`.`desc` like \'%'.mysql_real_escape_string($qsearch).'%\')';
	if($wh!='')$wh = " WHERE ".substr($wh,4)." AND `a`.`ctrl`<>".LINKEXCHANGE_CTRL_OVERWRITE;
	else $wh = " WHERE `a`.`ctrl`<>".LINKEXCHANGE_CTRL_OVERWRITE;
	if(is_int($top)) $lm = " LIMIT {$top}";else $lm="";
	$sql = "SELECT DISTINCT `a`.`id`,`a`.`name`,`a`.`title`,`a`.`url`,`a`.`src`,`a`.`desc`,DATE_FORMAT(`a`.`created`,'".DATETIME_FORMAT_DB."') as `created`,DATE_FORMAT(`a`.`lastupdate`,'".DATETIME_FORMAT_DB."') as `lastupdate`,`a`.`view`,`a`.`ctrl`
			FROM `".DB_TABLE_PREFIX."linkexchange` as `a` ".$tbcat." ".$wh." 
			ORDER BY `a`.".$sort.",`a`.`view` ASC,`a`.`id` ASC ".$lm;
	return mysql_query($sql);
}
function linkexchangepagelist($catid=null,$ctrl=null,$qsearch=null,$sort=null,&$page,&$pagecount,$pagesize=null){
	global $sql,$ESNC_ROWCOUNT,$ESNC_ROWSTART,$ESNC_ROWEND,$SORTBY;
	$sql="SHOW TABLES LIKE '".DB_TABLE_PREFIX."catlinkexchange'";
	$row=mysql_fetch_array(mysql_query($sql));if(($row[0]==null)||($row[0]==""))linkexchangesetup();
	if($sort==null)$sort = LINKEX_SORTBY_VIEW_ASC;
	$wh = '';$tbcat='';$sort = $SORTBY[$sort];
	if(is_int($catid)) $tbcat = " INNER JOIN `".DB_TABLE_PREFIX."catlinkexchangelinkexchange` as `b` ON `id` = `b`.`linkexchangeid` AND `b`.`catlinkexchangeid` = ".$catid;
	else $tbcat = " INNER JOIN `".DB_TABLE_PREFIX."catlinkexchangelinkexchange` as `b` ON `id` = `b`.`linkexchangeid` ";
	if(($ctrl!=null)&&(is_int($ctrl))&&($ctrl>0))
		if(!is_array($ctrl))$wh = ' AND `a`.`ctrl`='.(int)$ctrl;
		else{
			$tmp='';
			foreach($ctrl as $i)$tmp .= ' OR `a`.`ctrl`='.(int)$i;
			$wh .= " AND(".substr($tmp,3).")";
		}
	if($qsearch)$wh .= ' AND (`a`.`title` like \'%'.mysql_real_escape_string($qsearch).'%\' OR `a`.`url` like \'%'.mysql_real_escape_string($qsearch).'%\' OR `a`.`src` like \'%'.mysql_real_escape_string($qsearch).'%\' OR `a`.`desc` like \'%'.mysql_real_escape_string($qsearch).'%\')';
	if($wh!='')$wh = " WHERE ".substr($wh,4)." AND `a`.`ctrl`<>".LINKEXCHANGE_CTRL_OVERWRITE;
	else $wh = " WHERE `a`.`ctrl`<>".LINKEXCHANGE_CTRL_OVERWRITE;
	if($page <1) $page=1;
	if(($pagesize==null)||(!is_int($pagesize))||($pagesize < 1))$pagesize=100;
	$ESNC_ROWSTART=($page-1) * $pagesize;
	$sql = "SELECT SQL_CALC_FOUND_ROWS DISTINCT `a`.`id`,`a`.`name`,`a`.`title`,`a`.`url`,`a`.`src`,`a`.`desc`,DATE_FORMAT(`a`.`created`,'".DATETIME_FORMAT_DB."') as `created`,DATE_FORMAT(`a`.`lastupdate`,'".DATETIME_FORMAT_DB."') as `lastupdate`,`a`.`view`,`a`.`ctrl`
			FROM `".DB_TABLE_PREFIX."linkexchange` as `a` ".$tbcat." ".$wh. " 
			ORDER BY `a`.{$sort},`a`.`view` ASC,`a`.`id` ASC 
			LIMIT ".$ESNC_ROWSTART.','.$pagesize;
	$rs = mysql_query($sql);
	$sql = 'SELECT FOUND_ROWS()';
	$rs1 = mysql_query($sql);
	$row = mysql_fetch_row($rs1);
	$ESNC_ROWCOUNT = (int)$row[0];
	$pagecount = (int)ceil($ESNC_ROWCOUNT/$pagesize);
	$ESNC_ROWEND = $ESNC_ROWCOUNT + $pagesize;
	return $rs;
}
function linkexchangeopen($id){
	global $sql;
	$sql="SHOW TABLES LIKE '".DB_TABLE_PREFIX."catlinkexchange'";
	$row=mysql_fetch_array(mysql_query($sql));if(($row[0]==null)||($row[0]==""))linkexchangesetup();
	$o=null;
	if(is_int($id)){
		$sql = "SELECT DISTINCT `a`.`id`,`a`.`name`,`a`.`title`,`a`.`url`,`a`.`src`,`a`.`desc`,DATE_FORMAT(`a`.`created`,'".DATETIME_FORMAT_DB."') as `created`,DATE_FORMAT(`a`.`lastupdate`,'".DATETIME_FORMAT_DB."') as `lastupdate`,`a`.`view`,`a`.`ctrl`
				FROM `".DB_TABLE_PREFIX."linkexchange` as `a` WHERE `id`=".(int)$id;
		$o = mysql_fetch_object($rs = mysql_query($sql));
		mysql_free_result($rs);
	}
	return $o;
}
function linkexchangeadd($catid,$name=null,$email=null,$title=null,$iurl,$desc,$src){
	global $sql;
	$sql="SHOW TABLES LIKE '".DB_TABLE_PREFIX."catlinkexchange'";
	$row=mysql_fetch_array(mysql_query($sql));if(($row[0]==null)||($row[0]==""))linkexchangesetup();
	if(($catid!=null)&&(is_int($catid))&&($catid>0)){
		$url=URL_LINKEXCHANGE_SERVICES.'?usermail='.USER_EMAIL.'&userpass='.esnc_decode(USER_PASS).'&act='.ACT_ADD_LINKEXCHANGE.'&DMid='.DOMAIN_ID;
		$url.='&CDid='.$catid;
		if(($name!=null)&&($name!=''))$url.='&name='.urlencode($name);
		if(($email!=null)&&($email!=''))$url.='&email='.urlencode($email);
		if(($title!=null)&&($title!=''))$url.='&title='.urlencode($title);
		if(($iurl!=null)&&($iurl!=''))$url.='&url='.urlencode($iurl);
		if(($desc!=null)&&($desc!=''))$url.='&desc='.urlencode($desc);
		if(($src!=null)&&($src!=''))$url.='&src='.urlencode($src);
		echo $url;
		$xml_parser = xml_parser_create();
		$data = file_get_contents($url);
		xml_parse_into_struct($xml_parser, $data, $doc, $index);
		xml_parser_free($xml_parser);
		$rs = false;
		foreach ($doc as $elem) {
			if (($elem['type'] == 'complete')&&($elem['tag']=='RETURN')){
				if($elem['value']=='true')$rs=true;
			}
		}
		return $rs;
	}
}
?>