<?php 
require '../../config.php';
require '../config.php';
require PATH_ADMIN.'inc/common.php';
require PATH_ADMIN.'inc/session.php';
if(!$session->getaccess(SESSION_CTRL_ADMIN,MODULE_ORDER,ACCESS_READ|ACCESS_WRITE)){
	exit('<script language="javascript" type="text/javascript">window.top.location.href="'.URL_ROOT.'";</script>');
}
define('ORDER_FILE',PATH_GLOBAL.'order.php');
include_once ORDER_FILE;
if(!isset($ORDER_STATUS)) $ORDER_STATUS = &$ORDER_CTRL;
if($act == ACT_SAVE){
	$tmp_file=PATH_TEMP.getuniquename().'.txt';
	$fh = fopen($tmp_file,'w');
	$cart_ctrl = sprintf('0x%08X',(int)@array_sum($_POST['CART_CTRL']));
	fwrite($fh,"<?php //#generated by order setup process
define('ORDER_CTRL_RECEIVED',			0x00000001);
define('ORDER_CTRL_ALERT_CUSTOMER',		0x00000002);
define('ORDER_CTRL_ALERT_SALES',		0x00000004);
define('ORDER_CTRL_CONFIRMED',			0x00000008);
define('ORDER_CTRL_CANCELED',			0x00000010);
define('ORDER_CTRL_PENDING',			0x00000020);
define('ORDER_CTRL_DELIVERED',			0x00000040);
define('CART_CTRL',						{$cart_ctrl});
\$ORDER_CTRL=".var_export($_POST['CTRL'],TRUE).";
");	
	if(is_array($_POST['SHIP'])){
		fwrite($fh,'$ORDER_SHIPVIA='.var_export($_POST['SHIP'],TRUE));
		fwrite($fh,';
');
	}
	if(is_array($_POST['PAY'])){
		fwrite($fh,'$ORDER_PAYMETHOD='.var_export($_POST['PAY'],TRUE));
		fwrite($fh,';
');
	}
	fwrite($fh,'$ORDER_STATUS=array(');
	$quote=array('\\'=>'\\\\','\''=>'\\\'');
	foreach($_POST['CTRL'] as $key=>$value)
		fwrite($fh,"{$key}=>'".strtr($value,$quote)."',\r\n");
	if(is_array($_POST['STATUS']))
		foreach($_POST['STATUS'] as $key=>$value)
			if($value) fwrite($fh,"{$key}=>'".strtr($value,$quote)."',\r\n");
	fwrite($fh,');
');
	fwrite($fh,'?>');
	fclose($fh);
	chmod(ORDER_FILE,0700);
	if(rename(ORDER_FILE,PATH_TEMP.time().'~'.basename(ORDER_FILE))){
		rename($tmp_file,ORDER_FILE);
		$t=file_get_contents(ORDER_FILE);
		include PATH_ADMIN.'inc/dbcon.php';
		$sql = 'REPLACE INTO `'.DB_TABLE_PREFIX.'fs`(`name`,`content`) VALUES (\'application/order.php\',\''.mysql_real_escape_string($t).'\')';
		mysql_query($sql);
		dbclose();
	}
	chmod(ORDER_FILE,0500);
redirect(URL_SELF);
exit();
}
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<head><title>C&#7845;u h&igrave;nh &#273;&#417;n h&agrave;ng</title>
<base href="<?php echo URL_BASE_ADMIN ?>" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<style type="text/css">
th{font-size:11px;}
.tab{display:none;}
.tabactive{display:table-header-group;}
textarea{width:95%;height:100%;}
.tabhead{cursor:pointer;font-size:11px;font-weight:normal;color:black;}
.tabheadactive{cursor:pointer;font-size:11px;font-weight:bold;color:green;}
tbody.tab input,tbody.tabactive input{width:90%;}
FIELDSET.v_table1 LABEL{
	display:inline-block;
	width:100px;
}
FIELDSET.v_table2 INPUT.input{width:200px; margin:2px 0px 0px 0px;}
LEGEND{padding:0px 5px 0px 5px;}
</style>
<comment>
<style type="text/css">
FIELDSET.v_table1 LABEL{
	margin:3px 0px;
	display:-moz-inline-box;
	display:inline-block;
	width:100px;
}
</style>
</comment>
<link rel="stylesheet" type="text/css" href="images/style.css"/>
</head>

<body>
<form action="<?php echo URL_SELF ?>?act=<?php echo ACT_SAVE ?>" method="post" onsubmit="return checkForm(this);">
<table cellpadding="4" cellspacing="8">
	<tr valign="top">
	<td>
	<fieldset><legend>Gi&#7887; h&agrave;ng</legend>
	<input class="input_mini" type="checkbox" value="1" name="CART_CTRL[]" <?php if(CART_CTRL & 1) echo 'checked' ?> />Cho ph&eacute;p &#273;&#7863;t h&agrave;ng
	<br/><input class="input_mini" type="checkbox" value="2" name="CART_CTRL[]" <?php if(CART_CTRL & 2) echo 'checked' ?> />Y&ecirc;u c&#7847;u ch&#7845;p nh&#7853;n &#273;i&#7873;u ki&#7879;n mua h&agrave;ng
	<br/><input class="input_mini" type="checkbox" value="4" name="CART_CTRL[]" <?php if(CART_CTRL & 4) echo 'checked' ?> />Hi&#7875;n th&#7883; ph&#7847;n th&ocirc;ng tin ng&#432;&#7901;i nh&#7853;n h&agrave;ng
	<br/><input class="input_mini" type="checkbox" value="8" name="CART_CTRL[]" <?php if(CART_CTRL & 8) echo 'checked' ?> disabled /> Cho ph&eacute;p thanh to&aacute;n tr&#7921;c tuy&#7871;n
	</fieldset>
	<fieldset class="v_table1"><legend>Tr&#7841;ng th&aacute;i c&#417; b&#7843;n c&#7911;a &#273;&#417;n h&agrave;ng</legend>
	<label>RECEIVED</label><input type="text" class="input" value="<?php echo $ORDER_CTRL[1] ?>" name="CTRL[1]" /><br/>
	<label>ALERT CUSTOMER</label><input type="text" class="input" value="<?php echo $ORDER_CTRL[2] ?>" name="CTRL[2]" /><br/>
	<label>ALERT SALES</label><input type="text" class="input" value="<?php echo $ORDER_CTRL[4] ?>" name="CTRL[4]" /><br/>	
	<label>CONFIRMED</label><input type="text" class="input" value="<?php echo $ORDER_CTRL[8] ?>" name="CTRL[8]" /><br/>
	<label>CANCELED</label><input type="text" class="input" value="<?php echo $ORDER_CTRL[16] ?>" name="CTRL[16]" /><br/>
	<label>PENDING</label><input type="text" class="input" value="<?php echo $ORDER_CTRL[32] ?>" name="CTRL[32]" /><br/>
	<label>DELIVERED</label><input type="text" class="input" value="<?php echo $ORDER_CTRL[64] ?>" name="CTRL[64]" /><br/>
	</fieldset>
	<fieldset class="v_table2"><legend>C&aacute;c tr&#7841;ng th&aacute;i kh&aacute;c</legend>
<?php foreach($ORDER_STATUS as $key=>$value)
		if(!$ORDER_CTRL[$key]) echo '<input class="input" value="'.$value.'" name="STATUS['.$key.']" /><br/>';
	for($i = max($key + 1,1000),$j=0;$j < 6;++$j,++$i)
		echo '<input class="input" value="" name="STATUS['.$i.']" /><br/>';
?>
	</fieldset>
	</td>
	<td><!-- van chuyen-->
	<fieldset class="v_table2"><legend>Ph&#432;&#417;ng ph&aacute;p thanh to&aacute;n</legend>
<?php foreach($ORDER_PAYMETHOD as $key=>$value)
		echo '<input class="input" value="'.$value.'" name="PAY['.$key.']" /><br/>';
	for($i = $key + 1,$j=0;$j < 6;++$j,++$i)
		echo '<input class="input" value="" name="PAY['.$i.']" /><br/>';
?>
	</fieldset>
	</td>
<?php if(is_array($ORDER_SHIPVIA)){?><td>
	<fieldset class="v_table2"><legend>Ph&#432;&#417;ng ph&aacute;p v&#7853;n chuy&#7875;n</legend>
<?php foreach($ORDER_SHIPVIA as $key1=>$value)
		echo '<input class="input" value="'.$value.'" name="SHIP['.$key1.']" /><br/>';
	for($i = $key1 + 1,$j=0;$j < 6;++$j,++$i)
		echo '<input class="input" value="" name="SHIP['.$i.']" /><br/>';
?>
	</fieldset>
<?php }	?>
	
	</td></tr>
</table>
</form>
</body>
<script language="javascript" type="text/javascript">
var frmItem=document.getElementsByTagName('form').item(0);
var url_up='<?php echo URL_CWD ?>index.php';
function checkForm(){
	var r = document.getElementsByTagName('input');
	var n = r.length;
	for(i=0;i<n;++i) if(r.item(i).value == '') r.item(i).disabled=true; else htmlencode(r.item(i));
	return true;
}
function htmlencode(o){
	var s,ss,i,n;
	s=String(o.value);
	ss="";
	n=s.length;
	for(i=0;i<n;++i){
 		if((code=Number(s.charCodeAt(i))) > 128)
			ss += "&#" + code + ";";
		else{
			switch(c = s.charAt(i)){
			default:		 ss += c;
			}
		}
	}
	o.value=ss;
}
window.top.document.title=self.document.title;
</script>
<script language="javascript" type="text/javascript" src="js/js.php"></script>
<script language="javascript" type="text/javascript" src="js/library.js"></script>
<script language="javascript" type="text/javascript" src="js/item-script.js"></script>
<script language="javascript" type="text/javascript" src="<?php echo URL_ROOT ?>js/admin-overload.js"></script>
</html>