<?php //generated by esnc.net setup wizard
/**** MULTI WEBSITE SUPPORT. DISCOVER CONFIG ON DOMAIN NAME. MUST REMOVED ON DEPLOYMENT ****/
switch(strtolower($_SERVER['HTTP_HOST'])){
case 'www.escapetovietnam.com':
	return include 'd:/hosting/escapetovietnam/config.php';
case 'www.vinashinlines.com':
	return include 'd:/hosting/envinashin/config.php';
case 'vn.vinashinlines.com':
	return include 'd:/hosting/vinashinlines/config.php';
case 'www.thangdu.com':
	return include 'd:/hosting/thangdu/config.php';
case 'www.handyartvietnam.com':
	return include 'd:/hosting/handyartvietnam/config.php';	
case 'www.usfba.com':
	return include 'd:/hosting/usfba2/config.php';	
case 'www.dulichtrongoi.com':
	return include 'd:/hosting/dulichtrongoi/config.php';	
case 'www.vietnam-business.org':
	return include 'd:/hosting/vietnambusiness/config.php';	
case 'www.windowfilm.com.vn':
	return include 'd:/hosting/windowfilm/config.php';	
case 'en.windowfilm.com.vn':
	return include 'd:/hosting/windowfilm/en_config.php';	
case 'vn.windowfilm.com.vn':
	return include 'd:/hosting/windowfilm/config.php';	
case 'www.nagatex.edu.vn':
	return include 'd:/hosting/nagatex/config.php';	
case 'vietvaluetravel.esnc.net':
	return include 'd:/hosting/vietvaluetravel/config.php';	
case 'urenco.esnc.net':
	return include 'd:/hosting/urenco2/config.php';	
case 'enurenco.esnc.net':
	return include 'd:/hosting/urenco2/en/config.php';	
case 'waytohalong.esnc.net': 
	return include 'd:/hosting/waytohalong/config.php'; 
case 'new.esnc.net':
	return include 'd:/hosting/esnc2/config.php'; 
case 'true.esnc.net':
return include 'd:/hosting/true/config.php'; 
case 'waytosapa.esnc.net':
return include 'd:/hosting/waytosapa/config.php';
case 'tramexco.esnc.net':
return include 'd:/hosting/tramexco/config.php';
case 'cuutrotreem.esnc.net':
return include 'd:/hosting/cuutrotreem/config.php';
case 'waytomekong.esnc.net':
return include 'd:/hosting/waytomekong/config.php';

case 'encuutrotreem.esnc.net':
return include 'd:/hosting/encuutrotreem/config.php';

case 'www.esnc.net':
case 'web.esnc.net':
case 'localhost':
	if(preg_match('/\/demo\/([\w]+)\//',$_SERVER['SCRIPT_NAME'],$a)) {
		return include('d:/wwwroot/'.$a[1].'/config.php');
	}
//	return include 'd:/hosting/esnc/config.php';
}
?>