<?php //generated by esnc.net setup wizard
error_reporting(0);
$ss=strpos($_SERVER['HTTP_HOST'],'www');
if(trim($ss)==NULL) header('Location:http://www.'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI']);
set_magic_quotes_runtime(0);
define('DB_NAME','waytovietnam2009');
define('DB_HOST','mysqlv10');
define('DB_TYPE','mysql 5.0');
define('DB_TABLE_PREFIX','waytovietnamen_');
define('DB_USER','waytovietnam2009');
define('DB_PWD','bnh1YW52aW5o');

define('CHARSET','utf-8');

define('DB_USER_ADMIN','waytovietnam2009');
define('DB_PWD_ADMIN','bnh1YW52aW5o');

/***SECTION:MODULE DEFINITION ***/
define('MODULE_ORDER',		0x00000001);//0x00000001=order
define('MODULE_PRODUCT',	0x00000002);//0x00000002=product
define('MODULE_OPTION',	0x00000004);//0x00000004=product option
define('MODULE_PROMOTION',	0x00000008);//0x00000008=promotion
define('MODULE_NEWS',		0x00000010);//0x000000010=news
define('MODULE_UTILITY',	0x00000020);//0x000000020=utility
define('MODULE_FAQ',		0x00000040);//0x000000040=faq
define('MODULE_AGENT',		0x00000080);//0x000000080=agent
define('MODULE_FEEDBACK',	0x00000100);//0x000000100=feedback
define('MODULE_MARKETING',	0x00000200);//0x000000200=marketing
define('MODULE_BANNER',		0x00000400);//0x000000400=enable
define('MODULE_USER',		0x00000800);//0x000000800=enable
define('MODULE_POLL',		0x00001000);//0x000001000=poll
define('MODULE_JOB',		0x00002000);//0x000002000=job scheduler
define('MODULE_FILE',		0x00004000);//0x000004000=file editor
define('MODULE_SYS',		0x00008000);//0x000008000=sys
define('MODULE_MEMBER',		0x00010000);//0x00010000=member management
define('MODULE_QUOTE',		0x00020000);//0x000020000=quote management
define('MODULE_CRM',		MODULE_ORDER|MODULE_POLL|MODULE_MARKETING|MODULE_FEEDBACK|MODULE_FAQ|MODULE_MEMBER);


/**SECTION: FILE SYSTEM**/
define('PATH_ROOT',				'/data/16/1/66/19/1555345/user/1675010/htdocs/waytovietnam/');
define('PATH_CLASS',			'/data/16/1/66/19/1555345/user/1675010/htdocs/waytovietnam/esnc-upgrade/class/');
define('PATH_COMPLS',			'/data/16/1/66/19/1555345/user/1675010/htdocs/waytovietnam/esnc-upgrade/compls/');
define('PATH_INC',				'/data/16/1/66/19/1555345/user/1675010/htdocs/waytovietnam/esnc-upgrade/inc2/');
define('PATH_COMPONENT',		'/data/16/1/66/19/1555345/user/1675010/htdocs/waytovietnam/component/');

define('PATH_IMAGES',			'/data/16/1/66/19/1555345/user/1675010/htdocs/waytovietnam/images/');
define('PATH_MYIMAGES',			'/data/16/1/66/19/1555345/user/1675010/htdocs/waytovietnam/waytovietnam2009-images/');

define('PATH_PRODUCT_IMG1',		PATH_MYIMAGES.'product/img1/');
define('PATH_PRODUCT_IMG2',		PATH_MYIMAGES.'product/img2/');
define('PATH_PRODUCT_PACKAGE_IMG1',		PATH_MYIMAGES.'package/img1/');
define('PATH_PRODUCT_PACKAGE_IMG2',		PATH_MYIMAGES.'package/img2/');
define('PATH_PRODUCTPHOTO_IMG',	PATH_MYIMAGES.'product/photo/');
define('PATH_PRODUCT_DETAIL',	PATH_MYIMAGES.'product/detail/');
define('PATH_PRODUCT_META',		PATH_MYIMAGES.'product/meta/');
define('PATH_CATPRODUCT_IMG1',	PATH_MYIMAGES.'catproduct/img1/');
define('PATH_CATPRODUCT_META',	PATH_MYIMAGES.'catproduct/meta/');
define('PATH_NEWS_IMG1',		PATH_MYIMAGES.'news/img1/');
define('PATH_NEWS_IMG2',		PATH_MYIMAGES.'news/img2/');
define('PATH_NEWS_CONTENT',		PATH_MYIMAGES.'news/content/');
define('PATH_NEWS_META',		PATH_MYIMAGES.'news/meta/');
define('PATH_CATNEWS_IMG1',		PATH_MYIMAGES.'catnews/img1/');
define('PATH_CATNEWS_META',		PATH_MYIMAGES.'catnews/meta/');
define('PATH_UTILITY_IMG',		PATH_MYIMAGES.'utility/img/');
define('PATH_UTILITY_PATH',		PATH_MYIMAGES.'utility/path/');
define('PATH_CATUTILITY_IMG1',	PATH_MYIMAGES.'catutility/img1/');
define('PATH_CATBANNER_IMG1',		PATH_MYIMAGES.'catbanner/img1/');
define('PATH_BANNER_IMG',		PATH_MYIMAGES.'banner/img/');
define('PATH_AGENT_IMG',		PATH_MYIMAGES.'agent/img/');
define('PATH_APPLICATION',		PATH_MYIMAGES.'application/');
define('PATH_GLOBAL',			PATH_APPLICATION);
define('PATH_GALLERY',			PATH_MYIMAGES.'gallery/');
define('PATH_META',				PATH_MYIMAGES.'meta/');
define('PATH_TEMPLATES',		PATH_IMAGES.'templates/');

define('PATH_TEMP',				'/data/16/1/66/19/1555345/user/1675010/htdocs/waytovietnam/images/temp/');
define('PATH_BACKUP',			'/data/16/1/66/19/1555345/user/1675010/htdocs/waytovietnam/images/backup/');
define('PATH_ESNC',				'/data/16/1/66/19/1555345/user/1675010/htdocs/waytovietnam/images/temp/esnc/');
define('PATH_SESSION',			'/data/16/1/66/19/1555345/user/1675010/htdocs/waytovietnam/images/temp/session/');
define('PATH_ADMIN_SESSION',	'/data/16/1/66/19/1555345/user/1675010/htdocs/waytovietnam/images/temp/adminsess/');
define('PATH_CACHE',			'/data/16/1/66/19/1555345/user/1675010/htdocs/waytovietnam/images/temp/cache/');
define('PATH_DEBUG',			'/data/16/1/66/19/1555345/user/1675010/htdocs/waytovietnam/images/temp/debug/');
define('FILE_JOB_CTRL',		PATH_TEMP.'job_ctrl_file.xxx');


/**SECTION: URL DEFINITION**/
define('URL_ROOT',				'/');
define('URL_ADMIN',				'/esnc/');

define('URL_IMAGES',			'/images/');
define('URL_MYIMAGES',			'/waytovietnam2009-images/');

define('URL_PRODUCT_IMG1',		URL_MYIMAGES.'product/img1/');
define('URL_PRODUCT_IMG2',		URL_MYIMAGES.'product/img2/');
define('URL_PRODUCT_PACKAGE_IMG1',		URL_MYIMAGES.'package/img1/');
define('URL_PRODUCT_PACKAGE_IMG2',		URL_MYIMAGES.'package/img2/');
define('URL_PRODUCTPHOTO_IMG',		URL_MYIMAGES.'product/photo/');
define('URL_CATPRODUCT_IMG1',	URL_MYIMAGES.'catproduct/img1/');
define('URL_NEWS_IMG1',			URL_MYIMAGES.'news/img1/');
define('URL_NEWS_IMG2',			URL_MYIMAGES.'news/img2/');
define('URL_NEWS_PHOTO',		URL_MYIMAGES.'news/photo/');
define('URL_CATNEWS_IMG1',		URL_MYIMAGES.'catnews/img1/');
define('URL_UTILITY_IMG',		URL_MYIMAGES.'utility/img/');
define('URL_CATUTILITY_IMG1',	URL_MYIMAGES.'catutility/img1/');
define('URL_CATBANNER_IMG',		URL_MYIMAGES.'catbanner/img1/');
define('URL_BANNER_IMG',		URL_MYIMAGES.'banner/img/');
define('URL_AGENT_IMG',			URL_MYIMAGES.'agent/img/');
define('URL_APPLICATION',		URL_MYIMAGES.'application/');
define('URL_GALLERY',			URL_MYIMAGES.'gallery/');
define('URL_META',				URL_MYIMAGES.'meta/');
define('URL_TEMP',				'/data/16/1/66/19/1555345/user/1675010/htdocs/waytovietnam/images/temp/cache/');
define('URL_BASE',				'http://'.$_SERVER['HTTP_HOST'].URL_ROOT);
define('URL_SELF',			$_SERVER['SCRIPT_NAME']);
unset($_SERVER['SCRIPT_NAME']);//prevent use


/*****SECTION : SESSION PARAMETERS ****/

define('SESSION_TIMEOUT',	15);//session timeout in minutes
define('MAX_LOGON_TRIES',	5);
define('SESSION_NAME',		'PHPSESSIONIDESNC');
define('SESSION_CACHE',		'nocache');

/*****SECTION : SALE ITEM CLASSIFICATION ****/
define('SALES_CLASS_PRODUCT',1);

/*****SECTION : MESSAGING PARAMETERS ****/
define('MESSAGE_PROTO_SMTP',1);

/*****SECTION : FILE TYPE DEFINITION ****/
define('FILE_TYPE_IMAGE','|jpeg|jpg|gif|bmp|png|ico|');
define('FILE_TYPE_PLAINTEXT','|js|css|txt|rtf|');
define('FILE_TYPE_RICHTEXT','|htm|html|');
define('FILE_TYPE_FLASH','|swf|');
define('FILE_TYPE_WINDOWS_MOVIE','|avi|');
define('FILE_TYPE_ARCHIVE','|zip|rar|');
define('FILE_TYPE_CODE','|php|asp|asa|inc|ini|');

/*****SECTION : GENERAL PARAMETERS ****/
define('FORMAT_DATETIME','%d-%m-%Y %H:%M:%S');
define('FORMAT_DATE','%d-%m-%Y');
define('FORMAT_TIME','%H:%M:%S');
define('FORMAT_DB_DATETIME','%d-%m-%Y %T');
define('FORMAT_DB_DATE','%d-%m-%Y');
define('FORMAT_DB_TIME','%T');
define('FORMAT_ID_STRING','%06u');
define('FORMAT_PRODUCT_CODE','%8s');
define('REGEX_DATE','/^[^\d]*(\d{1,2})[^\d]+(\d{1,2})[^\d]+(\d{4}|\d{2})[^\d]*$/');
define('REGEX_TIME','/^[^\d]*(\d{1,2})[^\d]+(\d{1,2})[^\d]+(\d{0,3})[^\d]*$/');
define('REGEX_DATETIME','/^[^\d]*(\d{1,2})[^\d]+(\d{1,2})[^\d]+(\d{4}|\d{2})[^\d]+(\d{1,2})[^\d]+(\d{1,2})[^\d]+(\d{1,3}).*$/');
define('REGEX_EMAIL','/^[\w\.\-]@([a-zA-Z0-9\-]+\.)+[a-zA-Z]{2,5}$/');
define('REGEX_HREF','/href\=([\'\"])([^\'\"]+)\1/');
define('REGEX_CHECK_ID_SERIES','/^(\d+,)*\d+$/');
define('REGEX_CHECK_STRING_SERIES','/^(?:[\w\s\.\-]+,)*[\w\s\.\-]+$/');
define('REGEX_NORMAL_FILENAME','/[^a-zA-Z\d\.\-\_]+|_{2,}|(?:\.+(?=[^\.]*\.))|(?:\.+(?=\.))/');

/****SECTION: SORTBY_ **/
define('SORTBY_VIEW_DESC',1);
define('SORTBY_VIEW_ASC',0);
define('SORTBY_NAME_DESC',2);
define('SORTBY_NAME_ASC',3);
define('SORTBY_CREATED_DESC',5);
define('SORTBY_CREATED_ASC',4);
define('SORTBY_ID_DESC',7);
define('SORTBY_ID_ASC',6);
define('SORTBY_PRICE_DESC',9);
define('SORTBY_PRICE_ASC',8);

/***SECTION: TABLE ID**/
define('TABLE_CATPRODUCT',2);
define('TABLE_PRODUCT',1);
define('TABLE_CATNEWS',4);
define('TABLE_NEWS',3);
define('TABLE_CATBANNER',6);
define('TABLE_BANNER',5);
define('TABLE_CATUTILITY',8);
define('TABLE_UTILITY',7);
define('TABLE_FEEDBACK',9);
define('TABLE_CATAGENT',12);
define('TABLE_AGENT',11);
define('TABLE_FOLDER',14);
define('TABLE_FILE',13);
define('TABLE_ORDER',15);
define('TABLE_REPORT',17);
define('TABLE_USER',19);
define('TABLE_PROMOTION',21);
define('TABLE_QUOTE',23);
define('TABLE_OPTION',25);
define('TABLE_POLL',28);
define('TABLE_VOTE',27);
define('TABLE_CUSTOMER',29);
define('TABLE_FAQ',31);

/***SECTION: ACTION ID**/
define('ACT_OPEN',0);
define('ACT_LIST',1);
define('ACT_SEARCH',2);
define('ACT_ADD',3);
define('ACT_RENAME',4);
define('ACT_SET',5);
define('ACT_SETCTRL',ACT_SET);
define('ACT_UNSETCTRL',6);
define('ACT_MOVE',7);
define('ACT_COPY',8);
define('ACT_REORDER',9);
define('ACT_PRICE',10);
define('ACT_CLONE',11);
define('ACT_REMOVE',12);
define('ACT_DEL',ACT_REMOVE);
define('ACT_SAVE',13);
define('ACT_PASSWD',14);
define('ACT_DOWNLOAD',15);
define('ACT_RESTORE',16);
define('ACT_BACKUP',17);
define('ACT_REPORT',18);
define('ACT_EDIT',19);

/***SECTION: GENERAL**/
define('CAT_FLAG_ITEM',1);
define('CAT_FLAG_SUBCAT',2);
define('CAT_FLAG_EMPTY',0);
define('CAT_FLAG_ROOT',-1);
define('CAT_FLAG_NOEXIST',8);

/*****SECTION : CTRL MANGEMENT ****/
define('PRODUCT_CTRL_SHOW',		0x00000001);
define('PRODUCT_CTRL_NEW',		0x00000002);
define('PRODUCT_CTRL_SPECIAL',		0x00000004);
define('PRODUCT_CTRL_PRICECALL',	0x00000008);
define('PRODUCT_CTRL_BESTSOLD',		0x00000010);
define('PRODUCT_CTRL_UPCOMING',		0x00000020);
define('PRODUCT_CTRL_HOT',		0x00000040);
define('PRODUCT_CTRL_SALE',		0x00000080);
define('PRODUCT_CTRL_INSTOCK',		0x00000100);
define('PRODUCT_CTRL_FREE',		0x00000200);
//define('PRODUCT_CTRL_COUNT',		0x00000400);
//define('PRODUCT_CTRL_SHIPFREE',		0x00000800);
///define('PRODUCT_CTRL_SECHAND',		0x00001000);
define('PRODUCT_CTRL_FEATURED',		0x00002000);
//define('PRODUCT_CTRL_TOPMODEL',		0x00004000);
//define('PRODUCT_CTRL_OPTIONS',		0x00008000);
//define('PRODUCT_CTRL_VIRTUAL',		0x00010000);
//define('PRODUCT_CTRL_SALEOFF',		0x00020000);
///define('PRODUCT_CTRL_TOPHIT',		0x00040000);
//define('PRODUCT_CTRL_OFFER',		0x00080000);
//define('PRODUCT_CTRL_GUEST',		0x40000000);
$PRODUCT_CTRL=array(
	PRODUCT_CTRL_SHOW => 'Hien thi',
	PRODUCT_CTRL_NEW => 'special',
	PRODUCT_CTRL_SPECIAL => 'hot tour',
	PRODUCT_CTRL_PRICECALL => 'Tour tren trang hotel',
	PRODUCT_CTRL_BESTSOLD => 'Hot Hotel, Resort',
	PRODUCT_CTRL_SALE => 'Hotel, Resort tren trang chu',
	PRODUCT_CTRL_UPCOMING => 'New',
	PRODUCT_CTRL_HOT => 'visa ',
	//PRODUCT_CTRL_SALE => 'Khuyen mai',
	PRODUCT_CTRL_INSTOCK => 'last booking',
	PRODUCT_CTRL_FREE => 'Promotion',
	//PRODUCT_CTRL_COUNT => 'Hien thi o so luong',
	//PRODUCT_CTRL_SHIPFREE => 'Mien phi van chuyen',
	//PRODUCT_CTRL_SECHAND => 'Hang second-hand',
	PRODUCT_CTRL_FEATURED => 'Noi bat',
	//PRODUCT_CTRL_TOPMODEL => 'Top model',
	//PRODUCT_CTRL_OPTIONS => 'Co nhieu tuy chon gia',
	//PRODUCT_CTRL_VIRTUAL => 'Hang hoa ao (dich vu...)',
	//PRODUCT_CTRL_SALEOFF => 'Dang co khuyen mai',
	//PRODUCT_CTRL_TOPHIT => 'Nhieu nguoi xem',
	//PRODUCT_CTRL_OFFER => 'Offer',
	//PRODUCT_CTRL_GUEST => 'Public catalog',
);

define('PRODUCT_TYPE_TOUR',1700);
define('PRODUCT_TYPE_HOTEL',1800);
define('PRODUCT_TYPE_RESORT',1600);
define('PRODUCT_TYPE_TICKETA', 44);
define('PRODUCT_TYPE_VISA', 55);
define('PRODUCT_TYPE_TICKET', 43);
define('PRODUCT_TYPE_CAR', 16);
define('PRODUCT_TYPE_CARA', 160);
define('PRODUCT_TYPE_SERVICE',5);
define('PRODUCT_TYPE_SERVICE2',1900);
$PRODUCT_TYPE=array(
	PRODUCT_TYPE_TOUR=>'tour',
	PRODUCT_TYPE_HOTEL=>'hotel',
	PRODUCT_TYPE_RESORT=> 'Resort',
	PRODUCT_TYPE_SERVICE=>'service',
	PRODUCT_TYPE_SERVICE2=>'Cutomized',
	PRODUCT_TYPE_VISA=>'visa',
	PRODUCT_TYPE_TICKET=>'Kieu Ve may bay',
	PRODUCT_TYPE_TICKETA=>'Kieu Ve tau',
	PRODUCT_TYPE_CAR=>'Xe oto',
	PRODUCT_TYPE_CARA=>'Xe oto loai 2'
);
define('CATPRODUCT_CTRL_SHOW',		0x00000001);
define('CATPRODUCT_CTRL_HOT',		0x00020000);
define('CATPRODUCT_CTRL_MENU',		0x00000002);
define('CATPRODUCT_CTRL_MENUA',		0x00080000);
define('CATPRODUCT_CTRL_RESORT',	0x00800000);
define('CATPRODUCT_CTRL_HOME',		0x00000004);
define('CATPRODUCT_CTRL_GUEST',		0x40000000);
define('CATPRODUCT_CTRL_GUEST3',	0x00000400);
define('CATPRODUCT_CTRL_GUEST4',	0x00400000);
define('CATPRODUCT_CTRL_GUEST2',	0x00008000);
define('CATPRODUCT_CTRL_SERVICE',	0x00000040);

$CATPRODUCT_CTRL=array(
	CATPRODUCT_CTRL_SHOW => 'Hien thi',
	CATPRODUCT_CTRL_MENU => 'Tours',
	CATPRODUCT_CTRL_MENUA => 'Nhom-Tours',
	CATPRODUCT_CTRL_HOME => 'Hotels',
	CATPRODUCT_CTRL_GUEST => 'Trang chu',
	CATPRODUCT_CTRL_GUEST3 => 'Car',
	CATPRODUCT_CTRL_GUEST4 => 'Visa',
	CATPRODUCT_CTRL_GUEST2=> 'Dich vu khac',
	CATPRODUCT_CTRL_HOT => 'Noi bat',
	CATPRODUCT_CTRL_RESORT=>'Resort',
	CATPRODUCT_CTRL_SERVICE => 'Dich vu',
);
$CATPRODUCT_TYPE=array(
	0=>'Chung chung',
);
define('REVIEW_CTRL_SHOW',		0x00000001);
$REVIEW_CTRL=array(
	REVIEW_CTRL_SHOW => 'Hi&#7875;n th&#7883;',
);
define('PDLINK_CTRL_LINK',		0x00000001);
$PDLINK_CTRL=array(
	PDLINK_CTRL_LINK => 'Li&#234;n quan',
);
define('NEWS_CTRL_SHOW',		0x00000001);
define('NEWS_CTRL_EVENT',		0x00000002);
//define('NEWS_CTRL_DATA',		0x00000004);
//define('NEWS_CTRL_BRIEF',		0x00000008);
//define('NEWS_CTRL_FOCUS',		0x00000010);
//define('NEWS_CTRL_MESSAGE',		0x00000020);
//define('NEWS_CTRL_LETTER',		0x00000040);
//define('NEWS_CTRL_ABOUT',		0x00000080);
//define('NEWS_CTRL_MOSTREAD',		0x00000100);
//define('NEWS_CTRL_HOT',		0x00000200);
//define('NEWS_CTRL_FLASH',		0x00000400);
//define('NEWS_CTRL_HELP',		0x00000800);
//define('NEWS_CTRL_SELL',		0x00001000);
//define('NEWS_CTRL_BUY',		0x00002000);
//define('NEWS_CTRL_ACTIVE',		0x00004000);
//define('NEWS_CTRL_NOTITLE',		0x00040000);
///define('NEWS_CTRL_TRACE',		0x00080000);
//define('NEWS_CTRL_SMALLADS',		0x00100000);
$NEWS_CTRL=array(
	NEWS_CTRL_SHOW => 'hien thi',
	NEWS_CTRL_EVENT => 'Noi bat',
	//NEWS_CTRL_DATA => 'Bai viet',
	//NEWS_CTRL_BRIEF => 'Tin van',
	//NEWS_CTRL_FOCUS => 'Tin noi bat',
	//NEWS_CTRL_MESSAGE => 'Thong bao',
	//NEWS_CTRL_LETTER => 'Open letter',
	//NEWS_CTRL_ABOUT => 'Gioi thieu',
	//NEWS_CTRL_MOSTREAD => 'Doc nhieu nhat',
	//NEWS_CTRL_HOT => 'Tin nong',
	//NEWS_CTRL_FLASH => 'Xem nhanh',
	//NEWS_CTRL_NOTITLE => 'Khong hien thi title',
	//NEWS_CTRL_TRACE => 'Co hien thi ngay thang',
	//NEWS_CTRL_SMALLADS => 'Quang cao rao vat',
	//NEWS_CTRL_SELL => 'Quang cao ban',
	//NEWS_CTRL_BUY => 'Quang cao mua',
	//NEWS_CTRL_ACTIVE => 'Noi dung con thoi han',
	//NEWS_CTRL_HELP => 'Thong tin tro giup',
);
$NEWS_TYPE=array(
	0=>'N&#7897;i dung',
);
define('CATNEWS_CTRL_SHOW',		0x00000001);
define('CATNEWS_CTRL_SHOW2',	0x01000000);
define('CATNEWS_CTRL_SHOW3',	0x00010000);
define('CATNEWS_CTRL_SHOW4',	0x10000000);
define('CATNEWS_CTRL_MENU',		0x00000002);
define('CATNEWS_CTRL_MENU2',	0x00020000);
define('CATNEWS_CTRL_HOME',		0x00000004);
define('CATNEWS_CTRL_HOME2',	0x04000000);
define('CATNEWS_CTRL_POST',		0x00000400);
define('CATNEWS_CTRL_POST2',	0x00004000);
define('CATNEWS_CTRL_POST3',	0x00400000);
define('CATNEWS_CTRL_HELP',		0x00000800);
define('CATNEWS_CTRL_ADS',		0x00001000);
define('CATNEWS_CTRL_ADS2',		0x00080000);
define('CATNEWS_CTRL_USEFUL_INFO',0x00000080);

$CATNEWS_CTRL=array(
	CATNEWS_CTRL_SHOW => 'Hien thi',
	//CATNEWS_CTRL_MENU => 'Use-ful',
	CATNEWS_CTRL_MENU2 => 'Noi bat',
	CATNEWS_CTRL_HOME => 'News-event',
	//CATNEWS_CTRL_HOME2 => 'About',
	CATNEWS_CTRL_POST => 'FQAs',
	CATNEWS_CTRL_ADS => 'Careers',
	CATNEWS_CTRL_HELP => 'Travel-guide',
	//CATNEWS_CTRL_ADS2 => 'MICE',
	//CATNEWS_CTRL_SHOW2 =>'Privacy Policy',
	//CATNEWS_CTRL_SHOW3 => 'Terms & Conditions',
	///CATNEWS_CTRL_SHOW4 => 'business-travel',
	CATNEWS_CTRL_POST2 => 'Travel Agents',
	CATNEWS_CTRL_POST3 => 'Testimonials',
	CATNEWS_CTRL_USEFUL_INFO => 'User Infomation',
	
);

$CATNEWS_TYPE=array(
	0=>'Chung chung',
);
define('UTILITY_CTRL_SHOW',		0x00000001);
define('UTILITY_CTRL_NEW',		0x00000002);
define('UTILITY_CTRL_SPECIAL',		0x00000004);
define('UTILITY_CTRL_HOT',		0x00000040);
define('UTILITY_CTRL_SALE',		0x00000080);
define('UTILITY_CTRL_FEATURED',		0x00002000);
define('UTILITY_CTRL_TOPHIT',		0x00040000);
$UTILITY_CTRL=array(
	UTILITY_CTRL_SHOW => 'Hi&#7875;n th&#7883;',
);
$UTILITY_TYPE=array(
	0=>'Chung chung',
	1=>'Ph&#7847;n m&#7873;m',
	2=>'Nh&#7841;c chu&#244;ng',
	3=>'H&#236;nh n&#7873;n',
	4=>'T&#224;i li&#7879;u',
	5=>'Tr&#242; ch&#417;i',
);
define('CATUTILITY_CTRL_SHOW',		0x00000001);
$CATUTILITY_CTRL=array(
	CATUTILITY_CTRL_SHOW => 'Hien thi',
);
$CATUTILITY_TYPE=array(
	0=>'Chung chung',
);
define('BANNER_CTRL_SHOW',		0x00000001);
define('BANNER_CTRL_LOGO',		0x00400000);
define('BANNER_CTRL_ART',		0x00800000);
define('BANNER_CTRL_ADS',		0x01000000);
define('BANNER_CTRL_LINK',		0x02000000);
define('BANNER_CTRL_NEWWIN',		0x04000000);
define('BANNER_CTRL_SECURE',		0x08000000);
define('BANNER_CTRL_DISPLAY',		0x00080000);



$BANNER_CTRL=array(
	BANNER_CTRL_SHOW => 'Hien thi',
	BANNER_CTRL_LOGO => 'Logo',
	BANNER_CTRL_ART => 'Thu vien anh',
	BANNER_CTRL_ADS => 'Quang cao',
	BANNER_CTRL_LINK => 'Link exchange',
	BANNER_CTRL_DISPLAY => 'Dai dien cho nhom',

);
$BANNER_STATUS=array(
	1=>'&#272;&#7907;i tr&#7843; l&#7901;i',
	2=>'&#272;&#7907;i tr&#7843; l&#7901;i l&#7847;n 2',
	3=>'&#272;&#7907;i tr&#7843; l&#7901;i l&#7847;n 3',
	4=>'&#272;&#227; hi&#7879;n li&#234;n k&#7871;t c&#7911;a m&#236;nh',
	5=>'Ch&#7901; b&#7883; ghi &#273;&#232;',
);
define('CATBANNER_CTRL_SHOW',		0x00000001);
define('CATBANNER_CTRL_LOGO',		0x00000002);
define('CATBANNER_CTRL_TOP',		0x00000004);
define('CATBANNER_CTRL_LEFT',		0x00000008);
define('CATBANNER_CTRL_RIGHT',		0x00000010);
//define('CATBANNER_CTRL_BOTTOM',		0x00000020);
define('CATBANNER_CTRL_LINK',		0x00000040);
//define('CATBANNER_CTRL_LINK_VIP',		0x00000080);
define('CATBANNER_CTRL_FLOATLEFT',		0x00000100);
define('CATBANNER_CTRL_FLOATRIGHT',		0x00000200);
//define('CATBANNER_CTRL_SLOGAN',		0x00000400);
define('CATBANNER_CTRL_GALLERY',		0x00000800);
//define('CATBANNER_CTRL_HOME',		0x00001000);
//define('CATBANNER_CTRL_WEBLINK',		0x00002000);
//define('CATBANNER_CTRL_ROTATE',		0x00004000);
$CATBANNER_CTRL=array(
	CATBANNER_CTRL_SHOW => 'Hien thi',
	CATBANNER_CTRL_LOGO => 'Logo',
	CATBANNER_CTRL_LINK => 'Link Exchange',
	CATBANNER_CTRL_GALLERY => 'Thu vien anh',
	CATBANNER_CTRL_TOP => 'Ban do tour',
	CATBANNER_CTRL_FLOATLEFT => 'advertising',
	CATBANNER_CTRL_FLOATRIGHT => 'Box-img',
	CATBANNER_CTRL_LEFT => 'noi bat',
	CATBANNER_CTRL_RIGHT => 'Menu tour',
	//CATBANNER_CTRL_HOME => 'Home',
	//CATBANNER_CTRL_WEBLINK => 'Web link',
	//0x00000000 => 'Banner xoay vong',
);
$CATBANNER_TYPE=array(
	0=>'Chung chung',
);
define('AGENT_CTRL_SHOW',		0x00000001);
define('AGENT_CTRL_GOLD',		0x00000002);
define('AGENT_CTRL_PLATINUM',		0x00000004);
define('AGENT_CTRL_DIAMOND',		0x00000008);
$AGENT_CTRL=array(
	AGENT_CTRL_SHOW => 'Hi&#7875;n th&#7883;',
	AGENT_CTRL_GOLD => '&#272;&#7841;i l&#253; v&#224;ng',
	AGENT_CTRL_PLATINUM => '&#272;&#7841;i l&#253; b&#7841;ch kim',
	AGENT_CTRL_DIAMOND => '&#272;&#7841;i l&#253; kim c&#432;&#417;ng',
);
define('AGENT_TYPE_AGENT',0);
define('AGENT_TYPE_OFFICE',1000);
define('AGENT_TYPE_REPT',1001);
define('AGENT_TYPE_FACTORY',1002);
define('AGENT_TYPE_CUSTOMER',1010);
define('AGENT_TYPE_MEMBER',1020);
$AGENT_TYPE=array(
	AGENT_TYPE_AGENT => '&#272;&#7841;i l&#253;',
	1=>'&#272;&#7841;i l&#253; c&#7845;p 1',
	2=>'&#272;&#7841;i l&#253; c&#7845;p 2',
	AGENT_TYPE_OFFICE => 'V&#259;n ph&#242;ng,tr&#7909; s&#7903;',
	AGENT_TYPE_REPT => '&#272;&#7841;i di&#7879;n',
	AGENT_TYPE_FACTORY => 'Nh&#224; m&#225;y',
	AGENT_TYPE_CUSTOMER => 'Kh&#225;ch h&#224;ng',
	AGENT_TYPE_MEMBER => 'H&#7897;i vi&#234;n',
);
define('POLL_PERCENT_UNIT',	10);
define('POLL_CTRL_SHOW',		0x00000001);
$POLL_CTRL=array(
	POLL_CTRL_SHOW => 'Hien thi',
);
define('POLL_TYPE_MULTIPLE',2);
define('POLL_TYPE_EXCLUSIVE',1);
$POLL_TYPE=array(
	POLL_TYPE_EXCLUSIVE => 'M&#7897;t l&#7921;a ch&#7885;n',
	POLL_TYPE_MULTIPLE => 'Nhi&#7873;u l&#7921;a ch&#7885;n',
);
$USER_GENDER=array(
	0x00000001 => 'Nam',
	0x00000002 => 'N&#7919;',
);
define('USER_ALERT_ENABLE',		0x00000001);
define('USER_ALERT_ORDER',		0x00000002);
define('USER_ALERT_FEEDBACK',		0x00000004);
define('USER_ALERT_NEWFAQ',		0x00000008);
define('USER_ALERT_LINK',		0x00000010);
$USER_ALERT=array(
	USER_ALERT_ENABLE => 'B&#7853;t t&#237;nh th&#244;ng b&#225;o',
	USER_ALERT_ORDER => 'Nh&#7853;n th&#244;ng b&#225;o khi c&#243; &#273;&#417;n h&#224;ng',
	USER_ALERT_NEWFAQ => 'Nh&#7853;n th&#244;ng b&#225;o khi c&#243; c&#226;u h&#7887;i',
	USER_ALERT_FEEDBACK => 'Nh&#7853;n th&#244;ng b&#225;o khi c&#243; li&#234;n h&#7879;',
	USER_ALERT_LINK => 'Nh&#7853;n th&#244;ng b&#225;o khi c&#243; trao &#273;&#7893;i li&#234;n k&#7871;t',
);
define('JOB_CTRL_SHOW',		0x00000001);
define('JOB_CTRL_AUTODELETE',		0x00000004);
define('JOB_CTRL_RUNOW',		0x00000008);
$JOB_CTRL=array(
	JOB_CTRL_SHOW => 'C&#243; th&#7875; ch&#7841;y',
	JOB_CTRL_AUTODELETE => 'T&#7921; &#273;&#7897;ng xo&#225;',
	JOB_CTRL_RUNOW => 'Ch&#7841;y ngay',
);
$REPORT_CTRL=array(
	0x00000001 => 'C&#243; th&#7875; ch&#7841;y',
);
define('REPORT_TYPE_SYS',		0x00000001);
define('REPORT_TYPE_SQL',		0x00000002);
define('REPORT_TYPE_COLUMN',		0x00000004);
define('REPORT_TYPE_SUM',		0x00000008);
define('REPORT_TYPE_EXTERN',		0x00000010);
$REPORT_TYPE=array(
	REPORT_TYPE_SYS => 'H&#7879; th&#244;ng',
	REPORT_TYPE_SQL => 'SQL',
	REPORT_TYPE_COLUMN => 'Tr&#236;nh b&#224;y d&#7841;ng c&#7897;t',
	REPORT_TYPE_SUM => 'Hi&#7879;n t&#7893;ng s&#7889; d&#242;ng',
	REPORT_TYPE_EXTERN => 'B&#225;o c&#225;o ngo&#224;i',
);
define('CUSTOMER_CTRL_ACTIVE',		0x00000001);
define('CUSTOMER_CTRL_AGENT',		0x00000002);
define('CUSTOMER_CTRL_PASSWD',		0x00000040);
$CUSTOMER_CTRL=array(
	CUSTOMER_CTRL_ACTIVE => 'Cho ph&#233;p &#273;&#259;ng nh&#7853;p',
	CUSTOMER_CTRL_AGENT => 'T&#224;i kho&#7843;n &#273;&#7841;i l&#253;',
	CUSTOMER_CTRL_PASSWD => 'M&#7853;t kh&#7849;u h&#7871;t h&#7841;n',
);

/* ENABLE MODULE PACKAGEPRICE MODIFY PRICE_MANAGER_TYPE='enable'*/
define('PRICE_MANAGER_TYPE','enable');
define('N_PRODUCT_CF',11);
define('SQL_NOW','(NOW())');
date_default_timezone_set('Asia/Saigon');
require PATH_GLOBAL.'config.php';
include PATH_GLOBAL.'currency.php';
include PATH_GLOBAL.'order.php';
?>