<?php /*created by language editor*/

define('T_ABOUT_US','Testimonials');
define('T_NEWS_EVENTS','News & Events');
define('T_HOME','Home Page');
define('T_TERM_CONDITION','Terms & Conditions');
define('T_CONTACT','Contact Us');
define('T_LINK_EXCHANGE','Link exchange');
define('T_FAQ','FAQs');
define('T_HOT_NEWS','Special');
define('T_BOX_TESTIMONIAL','Testimonials');
define('T_VIEW_MORE','View more');
define('T_GROUP_TOUR_HOME','Combination Tours');
define('T_TOUR_PREFERER','Best Seller Tours');
define('T_MORE_TOUR','View more');
define('T_HOTEL_PREFERER','Hotels - Resorts');
define('T_USEFUL_INFO_HOT','Travel Guides (All)');
define('T_TOUR','Tour');
define('T_POLICY','Policy');
define('T_HOTEL','Hotel');
define('T_SERVICE','Service');
define('T_USEFUL_INFO','Travel Guides');
define('T_ATTRACTION','Attractions');
define('T_BOX_ABOUT_US','Why us ?');
define('T_BOX_GALLERY','Gallery');
define('T_TOP','Top');
define('T_TOUR_IN','Tour in');
define('T_HOTEL_IN','Hotel in');
define('T_TOP_GROUP_HOTEL','Top Hotels in');
define('T_STAR','Star');
define('T_PRICE_FROM','Prices
from');
define('T_NIGHTS','Nights');
define('T_DAYS','Days');
define('T_DESTINATION','Destinations');
define('T_NIGHT','Nights');
define('T_SELECT_PAGE','Select Page');
define('T_USEFUL_INFO_IN','Guide');
define('T_TOUR_BOOK','Request Detailed Price');
define('T_FROM_PRICE','From');
define('T_TOUR_FROM','Start');
define('T_TOUR_STOP','Finish');
define('T_SEND_FRIEND','Send to your friends');
define('T_PRIN','Print');
define('T_TOUR_INCLUDE','Price include');
define('T_TOUR_EXCLUDE','Price exclude');
define('T_GROUP_TOUR','Tours Programs');
define('T_TOUR_SIMILAR','Other Tours');
define('T_ADDRESS','Address');
define('T_HOTEL_BOOK','Request Detailed Price');
define('T_COUNTRY','Country');
define('T_HOTEL_DETAIL','Information in details');
define('T_HOTEL_SIMILAR','Other Hotels');
define('T_CITY','City');
define('T_GROUP_HOTEL','HOTEL');
define('T_LEFT_ARROW_KEY','left arrow key Next');
define('T_MOVE','Move');
define('T_CLOSE','Close');
define('T_NEXT','NEXT');
define('T_RIGHT_ARROW_KEY','right arrow key ');
define('T_RESET','Reset');
define('T_SUBMIT','Submit');
define('T_GALLERY_PRODUCT','Gallery');
define('T_GROUP_SERVICE','Service');
define('T_EMAIL_TOUR_BOOK_SUBJECT_ADMIN','Request tour price');
define('T_SENDNAME','Galatourist Vietnam');
define('T_EMAIL_TOUR_BOOK_SUBJECT','Request Tour Price');
define('TEXT_DESCRIPTION','GALATOURIST- Local Travel Agency offer professional service for combination tours of Vietnam, Cambodia, Laos & Thailand, Best Service & Price, Vietnam Cambodia tours, Cambodia and Vietnam tour, Vietnam Laos Cambodia tours, Indochina package tours');
define('TEXT_SITE_TITLE','Vietnam Cambodia tours, Cambodia and Vietnam tour, Indochina package tours');
define('TEXT_KEYWORD','vietnam cambodia tours, cambodia vietnam laos tours, vietnam laos cambodia tour, indochina package tour');
define('T_EMAIL_TOUR_CUSTOMIZE_SUBJECT_ADMIN','Customize tour');
define('T_EMAIL_TOUR_CUSTOMIZE_SUBJECT','Request customize tour');
define('T_EMAIL_HOTEL_BOOK_SUBJECT','Request hotel price');
define('T_EMAIL_HOTEL_BOOK_SUBJECT_ADMIN','Request hotel price');
define('T_TIME_CREATED','Update');
define('T_SOURCE','Source');
define('T_NEWS_EVENTS_SIMILAR','Others');
define('T_GROUP_USEFUL_INFO','Travel Guides');
define('T_EMAIL_CONTACT_SUBJECT_ADMIN','Customer contact');
define('T_EMAIL_CONTACT_SUBJECT','Customer contact');
define('T_SERVICE_BOOK','Request Detailed Price');
define('T_SERVICE_SIMILAR','Other Services');
define('T_GROUP_ATTRACTION','Attraction');
define('T_GROUP_LINK_EX','Link exchange');
define('T_EMAIL','Email');
define('T_NATIONAL','National');
define('T_POST','Posted');
define('T_EMAIL_TESTIMONIAL_SUBJECT','Clients testimonial');
define('T_EMAIL_TESTIMONIAL_SUBJECT_ADMIN','Clients testimonial');
define('T_SEARCH','Search');
define('T_SELECT_TOUR','All Tours');
define('T_SELECT_HOTEL','All Hotels');
define('T_PREVIOUS','Previous');
define('T_SEARCH_RESULT_TOUR','Tour Search Results');
define('T_KEYWORD','Keyword');
define('T_ALL','All');
define('T_HAVE_RESULT','Results:');
define('T_TYPE_TOUR','Tour Type');
define('T_SEARCH_RESULT_HOTEL','Hotel Search Results');
define('T_TYPE_HOTEL','Hotel Type');
define('T_BOX_SUPPORT','Support Online');
define('T_COPYRIGHT','Galatourist Co.,Ltd * 01-524/TCDL-GP LHQT');
define('T_TRAVEL_CONFERENCE','M.I.C.E');
define('T_ATTRACTION_LIST','Attraction list');
define('T_USEFUL_LIST','Useful information list');
define('T_ATTRACTION_HOT','Attraction');
define('T_TRAVEL_CONFERENCE_SIMILAR','Similar News');
define('T_MAIL_SEND_LINK_TO','Link sent by your friend');
define('T_MAIL_SEND_LINK_FROM','Link sent to your friend');
define('T_INFO_SIMILAR','Others to know');
define('T_REFRESH_IMAGE','Refresh');
define('T_VIETNAM_TOUR','Tours');
define('T_TOUR_DETAIL',' ');
define('T_TOUR_FEEDBACK','Comments on program');
define('T_EMAIL_FEEDBACK_TOUR','Comment on program from clients');
define('T_SEND_FEEDBACK','SEND YOUR COMMENT');
define('T_SEND_REVIEW_SUCESS','Your comments have been sent');
define('T_DETAIL_TOUR','Detailed Program');
define('T_TOUR_PRICE','Price include & exclude');
define('T_HOTEL_TOUR','Detailed Hotels');
define('T_SELECT_HOUR','Hour');
define('T_OVERVIEW_TOUR','Highlights & Brief');
define('T_EMAIL_CALLBACK_SUBJECT_ADMIN','Callback request');
define('T_EMAIL_CALLBACK_SUBJECT','Callback request to Galatourist');
define('T_TOUR_NEW','New Tours');
define('T_ON_TOP','Back to top');
define('T_H1_TITLE_SITE',' Vietnam - Cambodia - Laos - Thailand - Myanmar');
define('T_TOUR_CUSTOMIZE','Tour customize');
define('T_MENU','Menu');
define('T_VIDEO','Live reviews by Video');
define('ABOUT_US','montrez tous');?>